---
- hosts: worker,master 
  become: true
  roles:
  - kontainerd

- hosts: worker
  become: true
  tasks:
  - name: Enable ssh Password Authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: PasswordAuthentication no
      line: PasswordAuthentication yes
  
  - name: sshd restart
    service:
      name: sshd
      state: restarted
      enabled: true

- hosts: master 
  become: true 
  roles:
  - master

- hosts: master
  vars:
  - ansible_ssh_user: vagrant
  - ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  tasks:
  - name: Run Join script 
    script: /home/vagrant/join.sh
    delegate_to: worker
    become: true