---
- hosts: worker,master 
  become: true
  roles:
  - kontainerd

- hosts: master 
  become: true 
  roles:
  - master

- hosts: master
  vars:
  - ansible_ssh_user: vagrant
  - ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  tasks:
  - name: Run Join script 
    script: /home/vagrant/join.sh
    delegate_to: worker
    